url: http://aventyrsupplevelser.github.io

permalink: pretty

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: "sorsjon"
        values:
            layout: "sorsjon"
